---

- name: Deploy a web application
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python-pip
  become: yes

- name: Install MySQL database
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
  become: yes

- name: Start MySQL Service 
  service: 
    name: mysql 
    state: started
    enabled: yes
  become: yes

- name: Create Application database
  mysql_db:
    name: employee_db
    state: present 
  become: yes

- name: Create Database User
  mysql_user: 
    name: db_user
    password: Passw0rd
    priv:  '*.*:ALL'
    state: present 
    host: '%'
  become: yes

- name: Install Python Flash dependency
  pip:
    name:  "{{ item }}"
  with_items:
    - flask
    - flask-mysql
  become: yes

- name: Copy source
  copy:
    src: ../app.py
    dest: /opt/app.py
  become: yes

- name: Start Web Server 
  shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 & 
  become: yes